feat: 14-7.1.10 Fixed more syntax errors in pipeline and added a failcheck

diff --git a/.github/workflows/ci_test_build_and_push_docker_image.yml b/.github/workflows/ci_test_build_and_push_docker_image.yml
--- a/.github/workflows/ci_test_build_and_push_docker_image.yml
+++ b/.github/workflows/ci_test_build_and_push_docker_image.yml
@@ -54,10 +54,12 @@ jobs:
 
         - name: Test Docker image with health check
           run: |
-            docker run -d --name backend_test -p 8000:8000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} annaschwartzchas/chas_advance_backend:$IMAGE_TAG
+            docker run -d --name backend_test -p 8000:8000 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" annaschwartzchas/chas_advance_backend:${{ env.IMAGE_TAG }}
+            HEALTH_CHECK_PASSED=false
             for i in {1..10}; do
               if curl -s http://localhost:8000/health | grep -q "ok"; then
                 echo "Health check passed!"
+                HEALTH_CHECK_PASSED=true
                 break
               else
                 echo "Waiting for the container to start..."
@@ -66,7 +68,12 @@ jobs:
             done
             docker stop backend_test
             docker rm backend_test
+            if [ "$HEALTH_CHECK_PASSED" = false ]; then
+            echo "Health check failed after 10 attempts"
+            exit 1
+          env: 
+              DATABASE_URL: ${{ secrets.DATABASE_URL }}
         
         - name: Push Docker Image to Docker Hub
           run: |
-            docker push annaschwartzchas/chas_advance_backend:$IMAGE_TAG
+            docker push annaschwartzchas/chas_advance_backend:${{ env.IMAGE_TAG }}
